### ISSUE TITLE
bug: missing IEmailForwardingService Dependency

### ISSUE THREAD

**Issue by jacobpfickes** [strikewalker/reacher#12]
I believe a dependency for IEmailForwardingService is missing from DependencyInjection.cs. When trying to run the project I am getting the following error:

```
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Reacher.Common.Logic.IEmailIngestionService Lifetime: Scoped ImplementationType: Reacher.Common.Logic.EmailIngestionService': Unable to resolve service for type 'Reacher.Common.Logic.IEmailForwardingService' while attempting to activate 'Reacher.Common.Logic.EmailIngestionService'.) (Error while validating the service descriptor 'ServiceType: Reacher.Common.Logic.IInvoiceService Lifetime: Scoped ImplementationType: Reacher.Common.Logic.InvoiceService': Unable to resolve service for type 'Reacher.Common.Logic.IEmailForwardingService' while attempting to activate 'Reacher.Common.Logic.InvoiceService'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Reacher.Common.Logic.IEmailIngestionService Lifetime: Scoped ImplementationType: Reacher.Common.Logic.EmailIngestionService': Unable to resolve service for type 'Reacher.Common.Logic.IEmailForwardingService' while attempting to activate 'Reacher.Common.Logic.EmailIngestionService'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Reacher.Common.Logic.IEmailForwardingService' while attempting to activate 'Reacher.Common.Logic.EmailIngestionService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in /Volumes/dev/reacher2/src/Reacher.App/Program.cs:line 34
 ---> (Inner Exception #1) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Reacher.Common.Logic.IInvoiceService Lifetime: Scoped ImplementationType: Reacher.Common.Logic.InvoiceService': Unable to resolve service for type 'Reacher.Common.Logic.IEmailForwardingService' while attempting to activate 'Reacher.Common.Logic.InvoiceService'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Reacher.Common.Logic.IEmailForwardingService' while attempting to activate 'Reacher.Common.Logic.InvoiceService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)<---
```

**Comment by strikewalker** [comment]
Awesome! Thanks for fixing my bug!
